### ISSUE TITLE
Unable to display properly when using tigervnc to connect

### ISSUE THREAD

**Issue by fxzxmicah** [any1/wayvnc#329] opened 2024-08-31 15:10 UTC
Version: 
```
wayvnc is running:
  wayvnc: 0.8.0
  neatvnc: 0.8.1
  aml: 0.3.0
```
LOG:
```
Info: Capturing output HEADLESS-2
Info: >> Headless output 2 1536x864+0x0 Power:ON
DEBUG: ../src/server.c: 1939: Trying address: 127.0.0.1
DEBUG: ../src/server.c: 1959: Successfully bound to address
Info: Listening for connections on 127.0.0.1:5900
DEBUG: ../src/ctl-server.c: 808: Initializing wayvncctl socket: /run/user/1000/wayvncctl
Info: New client connection from 127.0.0.1: 0x564dfa31a3f0 (ref 1)
DEBUG: ../src/server.c: 825: Client chose security type: 1
Info: Starting screen capture
DEBUG: ../src/main.c: 1337: Client connected, new client count: 1
DEBUG: ../src/ctl-server.c: 940: Enqueueing client-connected event: {"id":"1","address":"127.0.0.1","username":null,"seat":"Hyprland","connection_count":1}
DEBUG: ../src/ctl-server.c: 967: Enqueued client-connected event for 0 clients
DEBUG: ../src/server.c: 1079: Client 0x564dfa31a3f0 set encodings: cursor,desktop-size,extended-desktop-size,qemu-extended-key-event,tight,copyrect,zrle,hextile,rre,copyrect,raw
Info: Choosing tight encoding for client 0x564dfa31a3f0
DEBUG: ../src/main.c: 799: Client resolution changed: 1536x798, capturing output HEADLESS-2 which is headless: yes
zwlr_output_configuration_head_v1#23: error 3: Invalid mode
ERROR: ../src/main.c: 503: Failed to dispatch pending
DEBUG: ../src/ctl-server.c: 940: Enqueueing detached event: {}
DEBUG: ../src/ctl-server.c: 967: Enqueued detached event for 0 clients
```

**Comment by any1** [comment] 2024-08-31 16:16
If you're running hyprland, this is a duplicate of #326

**Comment by fxzxmicah** [comment] 2024-08-31 16:48
Looks like that. I found a temporary solution: `RemoteResize=0`.

**Comment by any1** [comment] 2024-08-31 17:15
Can you maybe create an issue with Hyprland?

**Comment by fxzxmicah** [comment] 2024-09-03 01:30
Is it possible that one day, wayvnc no longer supports hyprland?

**Comment by any1** [comment] 2024-09-03 08:21
We implement protocols, not specific compositors. Talk with the hyprland people.

**Closed by any1** 2024-09-03 08:21 UTC
Labels: bug
