### ISSUE TITLE
Meson/Ninja incorrectly installing libaml.so.0 libneatvnc.so.0 on Ubuntu

### ISSUE THREAD

**Issue by Lyamc** [any1/wayvnc#86] opened 2021-02-26 01:10 UTC
```
$ meson build
$ sudo ninja -C build install

[snip]

ninja: Entering directory `build'
[70/71] Installing files.
Installing subprojects/aml/libaml.so.0.0.0 to /usr/local/lib/x86_64-linux-gnu
Installing subprojects/neatvnc/libneatvnc.so.0.0.0 to /usr/local/lib/x86_64-linux-gnu
Installing wayvnc to /usr/local/bin
Installing wayvnc.1 to /usr/local/share/man/man1
Installing /home/lyam/wayvnc/subprojects/aml/include/aml.h to /usr/local/include
Installing /home/lyam/wayvnc/subprojects/neatvnc/include/neatvnc.h to /usr/local/include
Installing /home/lyam/wayvnc/build/meson-private/aml.pc to /usr/local/lib/x86_64-linux-gnu/pkgconfig
Installing /home/lyam/wayvnc/build/meson-private/neatvnc.pc to /usr/local/lib/x86_64-linux-gnu/pkgconfig


$ ldd /usr/local/bin/wayvnc 
	linux-vdso.so.1 (0x00007ffe34197000)
	libaml.so.0 => not found
	libneatvnc.so.0 => not found
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f595843d000)
	libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f5958393000)
	libwayland-client.so.0 => /lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f5958382000)
	libxkbcommon.so.0 => /lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f595833f000)
	libpam.so.0 => /lib/x86_64-linux-gnu/libpam.so.0 (0x00007f595832b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f595813f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f59585b6000)
	libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007f5958133000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5958111000)
	libaudit.so.1 => /lib/x86_64-linux-gnu/libaudit.so.1 (0x00007f59580e0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f59580d9000)
	libcap-ng.so.0 => /lib/x86_64-linux-gnu/libcap-ng.so.0 (0x00007f59580cf000)
```

So it's looking in `/lib/x86_64-linux-gnu/` but ninja/meson sticks aml and neatvnc libraries in the default path: `/usr/local/lib/x86_64-linux-gnu/`

Also, meson/ninja will make a symlink to a symlink to the real thing for both aml and neatvnc

```
lyam@server:~$ ls wayvnc/build/subprojects/aml/
libaml.so                      (symlink to ./libaml.so.0)
libaml.so.0                    (symlink to libaml.so.0.0.0)
libaml.so.0.0.0              <-- real thing
libaml.so.0.0.0.p              (directory)
```

```
lyam@server:~$ ls wayvnc/build/subprojects/neatvnc/
config.h       
libneatvnc.so.0            (symlink to ./libneatvnc.so.0.0.0)
libneatvnc.so.0.0.0.p      (directory)
libneatvnc.so              (symlink to ./libneatvnc.so.0)
libneatvnc.so.0.0.0      <-- real thing
```

It works when I move `libneatvnc.so.0.0.0 --> /lib/x86_64-linux-gnu/libneatvnc.so.0` and `libaml.so.0.0.0 --> /lib/x86_64-linux-gnu/libaml.so.0`

**Comment by any1** [comment] 2021-02-27 21:52
Meson's default installation prefix is `/usr/local`. If you want things to be installed to `/usr`, use `meson build --prefix=/usr`. However, that's probably not what you want. Only packages should be installing straight to `/usr`. Unless you want to create an actual debian package, it's probably best to set the prefix to `/opt/wayvnc/` and then add `/opt/wayvnc/lib/` to `ld.so.conf` and run `ldconfig`, so that the libraries can be located.

You could add the `/usr/local` library paths to `ld.so.conf`, but if you install a bunch of stuff there, it's probably going to be full with garbage eventually.

**Comment by Lyamc** [comment] 2021-02-27 21:54
`/usr/local` is in my ld.so.conf

**Comment by any1** [comment] 2021-02-27 22:01
Oh, so you have `/usr/local/lib/x86_64-linux-gnu` in `ld.so.conf` and you've run `ldconfig`?

**Comment by any1** [comment] 2021-03-02 20:34
Ping? It's hard for me to know what others know, so it would be nice to know exactly what you did with your ld.so.conf.

**Comment by Lyamc** [comment] 2021-03-02 20:47
Nothing was ever added to ld.so.conf, and ldconfig was never run. This is what I have:

```
lyam@server:~$ cat /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf

lyam@server:~$ ls /etc/ld.so.conf.d/
fakeroot-x86_64-linux-gnu.conf  libc.conf  x86_64-linux-gnu.conf  zz_i386-biarch-compat.conf  zz_x32-biarch-compat.conf
lyam@server:~$ grep -r "" /etc/ld.so.conf.d/
/etc/ld.so.conf.d/x86_64-linux-gnu.conf:# Multiarch support
/etc/ld.so.conf.d/x86_64-linux-gnu.conf:/usr/local/lib/x86_64-linux-gnu
/etc/ld.so.conf.d/x86_64-linux-gnu.conf:/lib/x86_64-linux-gnu
/etc/ld.so.conf.d/x86_64-linux-gnu.conf:/usr/lib/x86_64-linux-gnu
/etc/ld.so.conf.d/fakeroot-x86_64-linux-gnu.conf:/usr/lib/x86_64-linux-gnu/libfakeroot
/etc/ld.so.conf.d/zz_x32-biarch-compat.conf:# Legacy biarch compatibility support
/etc/ld.so.conf.d/zz_x32-biarch-compat.conf:/libx32
/etc/ld.so.conf.d/zz_x32-biarch-compat.conf:/usr/libx32
/etc/ld.so.conf.d/zz_i386-biarch-compat.conf:# Legacy biarch compatibility support
/etc/ld.so.conf.d/zz_i386-biarch-compat.conf:/lib32
/etc/ld.so.conf.d/zz_i386-biarch-compat.conf:/usr/lib32
/etc/ld.so.conf.d/libc.conf:# libc default configuration
/etc/ld.so.conf.d/libc.conf:/usr/local/lib
```

```
lyam@server:~$ ldconfig
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
lyam@server:~$ sudo ldconfig
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Read-only file system
```

```
lyam@server:~$ ldconfig -p | grep neat
        libneatvnc.so.0 (libc6,x86-64) => /usr/local/lib/libneatvnc.so.0
        libneatvnc.so.0 (libc6,x86-64) => /usr/local/lib/x86_64-linux-gnu/libneatvnc.so.0
        libneatvnc.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libneatvnc.so.0
        libneatvnc.so (libc6,x86-64) => /usr/local/lib/x86_64-linux-gnu/libneatvnc.so
```

```
lyam@server:~$ ldconfig -p | grep aml
        libyaml-0.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libyaml-0.so.2
        libaml.so.0 (libc6,x86-64) => /usr/local/lib/libaml.so.0
        libaml.so.0 (libc6,x86-64) => /usr/local/lib/x86_64-linux-gnu/libaml.so.0
        libaml.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libaml.so.0
        libaml.so (libc6,x86-64) => /usr/local/lib/x86_64-linux-gnu/libaml.so
```

**Comment by elsiehupp** [comment] 2021-03-20 15:00
The workaround I used for this was running `meson build` and then `sudo ninja -C build install` in both the `aml` and `neatvnc` cloned repositories.

**Comment by Lyamc** [comment] 2021-03-24 02:11
I tried that, I still needed to run `sudo ldconfig`

Regardless, wayvnc it doesn't work for me yet 
```
wl_registry@2: error 0: invalid version for global wl_seat (17): have 5 wanted 7
ERROR: Virtual Pointer protocol not supported by compositor
ERROR: Failed to initialize wayland
```

Looks like I have to wait for Gnome to get its act together. Currently running 3.38.5 on 21.04

**Comment by elsiehupp** [comment] 2021-03-25 11:50
I got the same `ERROR: Failed to initialize wayland` but not the preceding two lines. I just switched from Ubuntu to Debian, though, so it will be interesting to see what difference that makes, considering Debian tends to adopt new versions of various packages faster than Ubuntu does.

**Comment by danshick** [comment] 2021-03-25 13:34
I don't think Gnome supports [all of the protocols](https://github.com/any1/wayvnc/tree/master/protocols) necessary for wayvnc to work (and likely won't).

https://gitlab.gnome.org/GNOME/mutter/-/tree/master/src/wayland

**Comment by any1** [comment] 2021-04-02 21:59
I fail to see what  the issue is. What has been described here appears to be normal behaviour.

**Closed by any1** 2021-04-02 21:59 UTC

**Comment by elsiehupp** [comment] 2021-04-03 12:52
@any1 if the existing instructions fail to account for the necessary dependencies, then there is still an outstanding issue with the instructions.

**Comment by danshick** [comment] 2021-04-03 15:25
What dependencies are missing from the instructions?

**Comment by elsiehupp** [comment] 2021-04-03 15:47
The two subprojects, `aml` and `neatvnc`, are not getting installed properly if you just run the bash script from https://github.com/any1/wayvnc/issues/81 (which should probably be provided as something like `bootstrap.sh`). Granted, this is more of an issue with the bash script than with the existing build instructions, which don’t really account for Debian or Ubuntu in any way. I can try and do a pull request with the bash script in the next day or two.

**Comment by any1** [comment] 2021-04-03 16:07
`bootstrap.sh` is not a bad idea.

About getting things installed, something along these lines should work:
```
meson build --prefix=/opt/wayvnc
ninja -C build
sudo ninja -C build install
echo "/opt/wayvnc/lib" | sudo tee /etc/ld.so.conf.d/wayvnc.conf
sudo ldconfig
```

Alternatively: link the subprojects statically:
```
meson build --prefix=/opt/wayvnc -Ddefault_library=static
ninja -C build
sudo ninja -C build install
```
