### ISSUE TITLE
Here's build commands for debian bullseye (testing track atm)

### ISSUE THREAD

**Issue by twitchyliquid64** [any1/wayvnc#81] opened 2020-12-23 00:53 UTC
Sharing in case they are useful. Feel free to put them on the readme/faq if you are inclined :)

```shell
#!/bin/bash

# Install dependencies
DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -y \
  build-essential make cmake autoconf git ninja-build meson scdoc pkg-config \
  zlib1g-dev libpixman-1-dev libturbojpeg0-dev libgbm-dev \
  libgnutls28-dev \
  libdrm-dev libdrm-common libxkbcommon-dev libxkbcommon-tools libxkbcommon0 \
  wayland-protocols waylandpp-dev wayland-scanner++ libwayland-dev

set -xe

# Build, copied straight from README
git clone https://github.com/any1/wayvnc.git
git clone https://github.com/any1/neatvnc.git
git clone https://github.com/any1/aml.git

mkdir wayvnc/subprojects
cd wayvnc/subprojects
ln -s ../../neatvnc .
ln -s ../../aml .
cd -

mkdir neatvnc/subprojects
cd neatvnc/subprojects
ln -s ../../aml .
cd -

cd wayvnc
meson build
ninja -C build
```

**Comment by any1** [comment] 2020-12-31 13:14
Thanks. Are waylandpp-dev and wayland-scanner++ actually needed? Seems odd given that this is not a C++ project.

**Comment by twitchyliquid64** [comment] 2020-12-31 20:12
Hmmm, I'll try without, I basically just skimmed the other distro instructions + the meson file and threw in anything I thought was related. I'll try without those three packages and report back.

**Comment by Lyamc** [comment] 2021-02-26 00:35
You're missing libpam0g-dev btw.

There's something wrong with the way that wayvnc looks for the libraries. Also, meson/ninja will make a symlink to a symlink to the real thing for both aml and neatvnc

```
lyam@server:~$ ls wayvnc/build/subprojects/aml/
libaml.so                      (symlink to ./libaml.so.0)
libaml.so.0                   (symlink to libaml.so.0.0.0)
libaml.so.0.0.0             <-- real thing
libaml.so.0.0.0.p          (directory)
```

```
lyam@server:~$ ls wayvnc/build/subprojects/neatvnc/
config.h       
libneatvnc.so.0            (symlink to ./libneatvnc.so.0.0.0)
libneatvnc.so.0.0.0.p   (directory)
libneatvnc.so               (symlink to ./libneatvnc.so.0)
libneatvnc.so.0.0.0      <-- real thing
```

I also edited the script to install it (changed `ninja -C build` to `sudo ninja -C build install`), ran into a problem

```
lyam@server:~$ ./wayvnc.sh 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
autoconf is already the newest version (2.69-14).
build-essential is already the newest version (12.8ubuntu3).
cmake is already the newest version (3.18.4-2ubuntu1).
git is already the newest version (1:2.30.0-1ubuntu1).
libdrm-common is already the newest version (2.4.104-1build1).
libdrm-dev is already the newest version (2.4.104-1build1).
libgbm-dev is already the newest version (20.3.4-1).
libgnutls28-dev is already the newest version (3.7.0-5ubuntu1).
libpam0g-dev is already the newest version (1.3.1-5ubuntu6).
libpixman-1-dev is already the newest version (0.40.0-1build2).
libwayland-dev is already the newest version (1.18.0-2~exp1.1).
libxkbcommon-dev is already the newest version (1.0.3-2).
libxkbcommon0 is already the newest version (1.0.3-2).
make is already the newest version (4.3-4ubuntu1).
pkg-config is already the newest version (0.29.2-1ubuntu1).
wayland-protocols is already the newest version (1.20-1).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu4).
libturbojpeg0-dev is already the newest version (2.0.3-0ubuntu2).
libxkbcommon-tools is already the newest version (1.0.3-2).
meson is already the newest version (0.57.0+really0.56.2-0.1).
ninja-build is already the newest version (1.10.1-1).
scdoc is already the newest version (1.11.1-1).
wayland-scanner++ is already the newest version (0.2.8-1).
waylandpp-dev is already the newest version (0.2.8-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ git clone https://github.com/any1/wayvnc.git
Cloning into 'wayvnc'...
remote: Enumerating objects: 210, done.
remote: Counting objects: 100% (210/210), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 1908 (delta 136), reused 149 (delta 85), pack-reused 1698
Receiving objects: 100% (1908/1908), 340.13 KiB | 1.43 MiB/s, done.
Resolving deltas: 100% (1351/1351), done.
+ git clone https://github.com/any1/neatvnc.git
Cloning into 'neatvnc'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 1363 (delta 18), reused 22 (delta 10), pack-reused 1327
Receiving objects: 100% (1363/1363), 840.58 KiB | 2.32 MiB/s, done.
Resolving deltas: 100% (950/950), done.
+ git clone https://github.com/any1/aml.git
Cloning into 'aml'...
remote: Enumerating objects: 700, done.
remote: Counting objects: 100% (700/700), done.
remote: Compressing objects: 100% (401/401), done.
remote: Total 700 (delta 354), reused 630 (delta 290), pack-reused 0
Receiving objects: 100% (700/700), 118.11 KiB | 780.00 KiB/s, done.
Resolving deltas: 100% (354/354), done.
+ mkdir wayvnc/subprojects
+ cd wayvnc/subprojects
+ ln -s ../../neatvnc .
+ ln -s ../../aml .
+ cd -
/home/lyam
+ mkdir neatvnc/subprojects
+ cd neatvnc/subprojects
+ ln -s ../../aml .
+ cd -
/home/lyam
+ cd wayvnc
+ meson build
The Meson build system
Version: 0.56.2
Source dir: /home/lyam/wayvnc
Build dir: /home/lyam/wayvnc/build
Build type: native build
Project name: wayvnc
Project version: 0.4.0
C compiler for the host machine: cc (gcc 10.2.1 "cc (Ubuntu 10.2.1-20ubuntu1) 10.2.1 20210220")
C linker for the host machine: cc ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Library m found: YES
Library rt found: YES
Library pam found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency pixman-1 found: YES 0.40.0
Dependency gbm skipped: feature screencopy-dmabuf disabled
Run-time dependency libdrm found: YES 2.4.104
Run-time dependency xkbcommon found: YES 1.0.3
Run-time dependency wayland-client found: YES 1.18.0

|Executing subproject neatvnc method meson 
|
|Project name: neatvnc
|Project version: 0.4.0
|C compiler for the host machine: cc (gcc 10.2.1 "cc (Ubuntu 10.2.1-20ubuntu1) 10.2.1 20210220")
|C linker for the host machine: cc ld.bfd 2.36.1
|Program git found: YES (/usr/bin/git)
|Dependency libdrm found: YES 2.4.104 (cached)
|Library m found: YES
|Dependency pixman-1 found: YES 0.40.0 (cached)
|Run-time dependency libturbojpeg found: YES 2.0.3
|Run-time dependency gnutls found: YES 3.7.0
|Run-time dependency zlib found: YES 1.2.11
|
||Executing subproject aml method meson 
||
||Project name: aml
||Project version: 0.2.0
||C compiler for the host machine: cc (gcc 10.2.1 "cc (Ubuntu 10.2.1-20ubuntu1) 10.2.1 20210220")
||C linker for the host machine: cc ld.bfd 2.36.1
||Program git found: YES (/usr/bin/git)
||Library rt found: YES
||Run-time dependency threads found: YES
||Header <sys/epoll.h> has symbol "epoll_create" : YES 
||Header <sys/event.h> has symbol "kqueue" : NO 
||Message: epoll backend chosen
||Build targets in project: 1
||Subproject aml finished.
|
|Configuring config.h using configuration
|Build targets in project: 2
|Subproject neatvnc finished.

Program wayland-scanner found: YES (/usr/bin/wayland-scanner)
Dependency wayland-client found: YES 1.18.0 (cached)
Checking for function "memfd_create" : YES 
Configuring config.h using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Build-time dependency scdoc found: YES 1.11.1
Program /usr/bin/scdoc found: YES (/usr/bin/scdoc)
Program sh found: YES (/usr/bin/sh)
Build targets in project: 5

wayvnc 0.4.0

  Subprojects
        aml: YES
    neatvnc: YES

Found ninja-1.10.1 at /usr/bin/ninja
+ cd build
+ sudo ninja install
[70/71] Installing files.
Installing subprojects/aml/libaml.so.0.0.0 to /usr/local/lib/x86_64-linux-gnu
Installing subprojects/neatvnc/libneatvnc.so.0.0.0 to /usr/local/lib/x86_64-linux-gnu
Installing wayvnc to /usr/local/bin
Installing wayvnc.1 to /usr/local/share/man/man1
Installing /home/lyam/wayvnc/subprojects/aml/include/aml.h to /usr/local/include
Installing /home/lyam/wayvnc/subprojects/neatvnc/include/neatvnc.h to /usr/local/include
Installing /home/lyam/wayvnc/build/meson-private/aml.pc to /usr/local/lib/x86_64-linux-gnu/pkgconfig
Installing /home/lyam/wayvnc/build/meson-private/neatvnc.pc to /usr/local/lib/x86_64-linux-gnu/pkgconfig
```

Looks good. I run `wayvnc` and get this error:

```
$ wayvnc
wayvnc: error while loading shared libraries: libaml.so.0: cannot open shared object file: No such file or directory
```
It works when adding LD_LIBRARY_PATH
```
LD_LIBRARY_PATH=/usr/local/lib wayvnc
```

Now the build directories can be removed:
```
rm -Rf wayvnc neatvnc aml
```

**Comment by elsiehupp** [comment] 2021-03-20 15:14
To get this running on Ubuntu (20.10) I had to add a few more steps:
```
$ sudo apt install graphviz \
                   libdrm-dev \
                   libpam0g-dev \
                   libturbojpeg-dev \
                   libxcb-xkb-dev \
                   scdoc \
                   valgrind

$ sudo dpkg --purge --force-all libxkbcommon0
$ sudo dpkg --purge --force-all libxkbcommon0:i386
$ wget http://ftp.br.debian.org/debian/pool/main/libx/libxkbcommon/libxkbcommon0_1.0.3-2_amd64.deb
$ sudo dpkg --install libxkbcommon0_1.0.3-2_amd64.deb

$ sudo dpkg --purge --force-all libxkbcommon-dev
$ sudo dpkg --purge --force-all libxkbcommon-dev:i386
$ wget http://ftp.br.debian.org/debian/pool/main/libx/libxkbcommon/libxkbcommon-dev_1.0.3-2_amd64.deb
$ sudo dpkg --install libxkbcommon-dev_1.0.3-2_amd64.deb

$ sudo dpkg --purge --force-all libsdl2-2.0-0:i386
$ wget http://ftp.br.debian.org/debian/pool/main/libs/libsdl2/libsdl2-2.0-0_2.0.14+dfsg2-3_amd64.deb
$ sudo dpkg --install libsdl2-2.0-0_2.0.14+dfsg2-3_amd64.deb

$ sudo dpkg --purge --force-all libsdl2-dev:i386
$ wget http://ftp.br.debian.org/debian/pool/main/libs/libsdl2/libsdl2-dev_2.0.14+dfsg2-3_amd64.deb
$ sudo dpkg --install libsdl2-dev_2.0.14+dfsg2-3_amd64.deb

$ sudo dpkg --purge --force-all libxkbcommon-x11-0
$ wget http://ftp.br.debian.org/debian/pool/main/libx/libxkbcommon/libxkbcommon-x11-0_1.0.3-2_amd64.deb
$ sudo dpkg --install libxkbcommon-x11-0_1.0.3-2_amd64.deb

$ sudo apt --fix-broken install
$ sudo apt autoremove

$ cd <path_to_cloned_directory>/aml
$ meson build
$ sudo ninja -C build install

$ cd <path_to_cloned_directory>/neatvnc
$ meson build
$ sudo ninja -C build install
```
(These steps can probably be further simplified.)

To summarize, the issues were:
1. Ubuntu seems to have slightly different names for certain `apt` packages.
2. Ubuntu ships with a comedically outdated version of `xkbcommon`.
3. The `wayvnc` install script doesn't install `libaml.so.0` or `libneatvnc.so.0` properly (see #86), so you have to install them individually.

Now the issue I'm running into is that my graphics drivers don't seem to support Wayland, though it sounds like this will be fixed with [NVIDIA's upcoming 470 driver release](https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-GL-VLK-XWayland). (It seems that NVIDIA has pulled the 470 beta from distribution, though, due to the fact that it unlocked Ethereum mining on Windows.) My guess as to why I had previously gotten Wayland running on my computer is that I may have been using the open-source Nouveau driver, which comes with its own set of problems.

**Comment by Lyamc** [comment] 2021-03-20 15:29
I’ll test this out on 21.04

**Comment by elsiehupp** [comment] 2021-03-22 05:33
FWIW I don't know if there are any other problems caused by manually upgrading `xkbcommon`. Ideally the install script would be able to use a version other than the one included with the operating system. (I don't know how to do this off the top of my head.)

**Comment by elsiehupp** [comment] 2021-03-22 06:27
Another approach might be including `xkbcommon` as a subproject, like so:
```bash
$ git clone https://github.com/xkbcommon/libxkbcommon.git
$ cd wayvnc/subprojects
$ ln -s ../../libxkbcommon .
$ cd -
```
Then replacing the following line in `meson.build`:
https://github.com/any1/wayvnc/blob/7a60ab7db8fa1ac78987c312d14780cf5f178df7/meson.build#L47

with:
```Meson
xkbcommon = subproject('libxkbcommon', required: true)
```
This would work around the problem of Ubuntu (and possibly other distributions) not including recent enough versions of `xkbcommon`.

**Closed** 2021-04-02 21:49 UTC
