### ISSUE TITLE
Key inputs being lost

### ISSUE THREAD

**Issue by nifker** [any1/wayvnc#9] opened 2020-01-25 10:57 UTC
Sometimes in a session specific keys are getting lost(or not being handled) e.g. 's', ':' on a German layout.
I don't think its the vnc viewer because I tried different ones so far - but I am unsure how I can debug this issue.

**Comment by nifker** [comment] 2020-01-25 11:00
EDIT: I am even unable to press the keys on the vnc server's device when stopping the vnc server - this is not something I experienced before using this vnc server.

**Comment by any1** [comment] 2020-01-25 11:20
Is this perhaps a duplicate of #6?

**Comment by nifker** [comment] 2020-01-25 11:21
I have set the layout using the --layout parameter, so this shouldn't be problem, or?

**Comment by any1** [comment] 2020-01-25 11:29
Did you mean `--keyboard`?

**Comment by nifker** [comment] 2020-01-25 11:30
Uhm yes it was --keyboard.

**Comment by any1** [comment] 2020-01-25 11:39
Creating and selecting a seat should take care of your second issue of the keyboard layout of the compositor being overridden.
Because VNC sends symbols, but wayland expects key-codes, the server has to look up the in reverse based on the keymap but these are not always one-to-one, so I guess some effort must be put into identifying troublesome keys. I myself only know the Icelandic layout and that seems to be working fine. Are there any other keys than the ones that you specified that do not work?

**Comment by any1** [comment] 2020-01-25 12:24
I've identified a problem now which may be the cause of what you are experiencing. I think I know how to solve it.

**Comment by any1** [comment] 2020-01-25 13:25
I've pushed some changes that solve a issue that I found while investigating this. Is your problem solved too?

**Comment by nifker** [comment] 2020-01-25 13:29
I will test this a bit, as this issue doesn't happen instantly when starting the server.

**Comment by chron-isch** [comment] 2020-01-28 13:46
nifker: It happens when a client connects to the server. Currently still experimenting, I was having the same issue.

For me it was pretty random which keys were swallowed. (Q, R, P, ;, Y)

**Comment by any1** [comment] 2020-01-28 14:39
> nifker: It happens when a client connects to the server.

There's single keyboard state per VNC server instance. Multiple client connections could cause inconsistencies. Also, clients are disconnected without resetting the keyboard state. These would probably be solved by putting each client in it's own seat, but this requires #3 to be completed.

**Comment by chron-isch** [comment] 2020-01-28 18:31
@any1 That seems to have fixed it for me. Thank you.

**Comment by any1** [comment] 2020-03-05 17:11
@nifker, @chron-isch, Is this still an issue?

**Comment by nifker** [comment] 2020-03-05 17:22
I can confirm that this is an issue anymore.

**Comment by any1** [comment] 2020-03-05 17:46
Heh, did you mean to say "not an issue anymore"?

**Closed** 2020-03-07 14:23 UTC
Labels: bug
