### ISSUE TITLE
segfault when attached display changes dpms state

### ISSUE THREAD

**Issue by gleachkr** [any1/wayvnc#65] opened 2020-09-11 15:07 UTC
I'm encountering a segfault when starting wayvnc from within an ssh session, even with WAYLAND_DISPLAY and SWAYSOCK set. wayvnc is 0.2.0, neatvnc is 0.2.0, and aml is 0.1.0.

I expect this isn't hard to reproduce, but if it is please let me know.

**Comment by any1** [comment] 2020-09-11 15:49
A backtrace would be helpful.

**Comment by gleachkr** [comment] 2020-09-27 18:58
Seems to be fixed with an upgrade to neatvnc 0.3.2. Thanks!

**Comment by gleachkr** [comment] 2020-09-30 03:24
Looks like I was mistaken, the segfault is still occurring.

I've narrowed it down a bit. The segfault occurs when the monitor of the remote has been powered down via `swaymsg 'output * dpms off'`. It can be avoided by setting `swaymsg 'output * dpms on'`. So it's likely that the output state is the issue, rather than the access via ssh.

**Comment by any1** [comment] 2020-10-15 23:03
This might be a duplicate of #45.

**Comment by Arnavion** [comment] 2020-12-18 23:26
It happens to me any time I start wayvnc with `-o` set to an output that is currently dpms'd off.

```
(gdb) bt
#0  0x00007f30cfa4f0e4 in pixman_region_clear (region=region@entry=0x48) at pixman-region.c:2338
#1  0x000055825f18e596 in wv_buffer_damage_clear (self=0x0) at ../src/buffer.c:289
#2  wv_buffer_pool_release (pool=0x5582602bb3f0, buffer=0x0) at ../src/buffer.c:383
#3  0x000055825f18e67a in screencopy_failed (data=0x7fff60b7c1d0, frame=<optimized out>) at ../src/screencopy.c:194
#4  0x00007f30cf78f42d in ffi_call_unix64 () at ../src/x86/unix64.S:106
#5  0x00007f30cf78b4f9 in ffi_call_int (cif=<optimized out>, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=<optimized out>) at ../src/x86/ffi64.c:669
#6  0x00007f30cf9e08fe in wl_closure_invoke (closure=closure@entry=0x5582602a05a0, target=<optimized out>, target@entry=0x5582602cd440, opcode=opcode@entry=3, data=<optimized out>, flags=<optimized out>) at src/connection.c:1018
#7  0x00007f30cf9e0fcb in dispatch_event (display=display@entry=0x55826029c390, queue=<optimized out>, queue=<optimized out>) at src/wayland-client.c:1445
#8  0x00007f30cf9e119c in dispatch_queue (queue=0x55826029c460, display=0x55826029c390) at src/wayland-client.c:1591
#9  wl_display_dispatch_queue_pending (display=0x55826029c390, queue=0x55826029c460) at src/wayland-client.c:1833
#10 0x00007f30cf9e2963 in wl_display_dispatch_queue (queue=<optimized out>, display=<optimized out>) at src/wayland-client.c:1809
#11 0x00007f30cf9e297c in wl_display_dispatch (display=<optimized out>) at src/wayland-client.c:1876
#12 0x000055825f18c45f in main (argc=<optimized out>, argv=<optimized out>) at ../src/main.c:946

(gdb) frame 3
#3  0x000055825f18e67a in screencopy_failed (data=0x7fff60b7c1d0, frame=<optimized out>) at ../src/screencopy.c:194
194             wv_buffer_pool_release(self->pool, self->front);

(gdb) p *self
$5 = {status = SCREENCOPY_STOPPED, pool = 0x5582602bb3f0, front = 0x0, back = 0x0, manager = 0x5582602a12e0, frame = 0x0, version = 3, userdata = 0x7fff60b7c130, on_done = 0x55825f18eef0 <on_capture_done>, last_time = 0, start_time = 652923356779, timer = 0x5582602ba0c0,
  delay_smoother = {time_constant = 0.5, last_time = 0, last_result = 0}, delay = 0, is_immediate_copy = false, overlay_cursor = true, wl_output = 0x5582602a2710, wl_shm_width = 0, wl_shm_height = 0, wl_shm_stride = 0, wl_shm_format = WL_SHM_FORMAT_ARGB8888,
  have_linux_dmabuf = false, dmabuf_width = 0, dmabuf_height = 0, fourcc = 0, rate_limit = 30}

(gdb) frame 1
#1  0x000055825f18e596 in wv_buffer_damage_clear (self=0x0) at ../src/buffer.c:289
289             pixman_region_clear(&self->damage);

(gdb) p self
$7 = (struct wv_buffer *) 0x0
```

I guess one of `screencopy_failed` or `wv_buffer_damage_clear` or `wv_buffer_damage_clear` need to short-circuit when the front buffer is `NULL`.

**Closed** 2020-12-19 12:53 UTC
Labels: bug
