### ISSUE TITLE
Raspberry Pi OS - multiple monitors issue

### ISSUE THREAD

**Issue by antoniotvr** [any1/wayvnc#292] opened 2024-02-20 08:25 UTC
Hi.

Yesterday I have installed the latest version of Raspberry Pi OS downloaded from the main website of the project.

I have installed the image on Raspberry PI 4 and activated the vnc.

VNC connection works fine but the problem is that the dual monitor is not managed in the proper way.

In every vnc client that I have tested (realvnc viewer or tightvnc for example) you can only see one monitor and also the monitor that you see is not rendering what do you see in the real output of raspberry.

So you have to move blindly and is not possible to do any tastk through vnc connection.

Thank you

**Comment by any1** [comment] 2024-02-20 10:03
Multiple monitors in the same client window are not implemented yet, although you can cycle between them using a key binding of your own choice. See: https://github.com/any1/wayvnc/issues/112#issuecomment-1312663912

**Comment by any1** [comment] 2024-11-02 22:18
This is a duplicate of #226

**Closed by any1** 2024-11-02 22:18 UTC
Labels: duplicate
