### ISSUE TITLE
Cant start it - error Failed to initialize renderer

### ISSUE THREAD

**Issue by waligu** [any1/wayvnc#41] opened 2020-05-14 02:23 UTC
I use Gentoo compiled nearly without any X protocol in it

After starting wayvnc those both messages came up 

DEBUG: OpenGL ES 3.2 Mesa 20.0.6
ERROR: Failed to initialise renderer

i don't get what is missing or what he trys to initialise. There is no log

**Comment by any1** [comment] 2020-05-18 20:05
Can you run `glxinfo` from the `mesa-progs` package and post the results here?

**Comment by any1** [comment] 2020-05-18 20:20
This might be a duplicate of #24.

**Comment by waligu** [comment] 2020-05-19 01:26
[glx.txt](https://github.com/any1/wayvnc/files/4647733/glx.txt)

**Comment by waligu** [comment] 2020-05-19 01:26
that are the results from the run

**Comment by any1** [comment] 2020-07-11 21:02
This is no longer relevant as OpenGL is no longer used for rendering.

**Closed by any1** 2020-07-11 21:02 UTC
